# Build with: docker build -t rails-testing -f Dockerfile.testing .
# Use the image to run and test your app in a clean consistent container.
# Example: docker run --rm -it -v $PWD:/app -p 3000:3000 rails-testing
FROM ruby:3.1.2-alpine3.16

# Add required packages.
RUN apk add --no-cache build-base tzdata nodejs yarn sqlite-dev postgresql-dev mysql-dev git
RUN gem install rails:7.0.4 bundler:2.3.23

# Add user and configure directory.
RUN adduser -D rails
USER rails
WORKDIR /app
VOLUME /app

COPY --chown=rails ./entrypoint.sh /entrypoint.sh

ENV RAILS_ENV=test
ENV GEM_HOME=/home/rails/gems

EXPOSE 3000
ENTRYPOINT [ "/entrypoint.sh" ]
