version: '3.3'

services:
  ghost:
    image: ghost:5.91.0
    restart: always
    ports:
      - 4278:2368 # Internal server listens on port 2368.
    env_file:
      - "env"
    volumes:
      - content:/var/lib/ghost/content
    depends_on:
      - db

  db:
    image: mariadb:11.5.2
    restart: always
    env_file:
      - "env"
    volumes:
      - db:/var/lib/mysql

volumes:
  content:
  db:
